version: "3.7"

services:
  sms:
    # service 1 container name
    container_name: react-prod
    build:
     
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "99:3000"
   
    volumes:
      - "/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=production
